# Default example-webhook
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webhook-dnspod.fullname" . }}
  labels:
{{ include "webhook-dnspod.labels" . | indent 4 }}
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "webhook-dnspod.fullname" . }}:webhook-authentication-reader
  namespace: kube-system
  labels:
{{ include "webhook-dnspod.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "webhook-dnspod.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "webhook-dnspod.fullname" . }}:auth-delegator
  labels:
{{ include "webhook-dnspod.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "webhook-dnspod.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "webhook-dnspod.fullname" . }}:domain-solver
  labels:
{{ include "webhook-dnspod.labels" . | indent 4 }}
rules:
  - apiGroups:
      - {{ .Values.groupName }}
    resources:
      - '*'
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "webhook-dnspod.fullname" . }}:domain-solver
  labels:
{{ include "webhook-dnspod.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "webhook-dnspod.fullname" . }}:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Values.certManager.serviceAccountName }}
    namespace: {{ .Values.certManager.namespace }}
---
# The missing rbac of the official webhook-example
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "webhook-dnspod.secretReader" . }}
  labels:
{{ include "webhook-dnspod.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  resourceNames:
  - "dnspod-credentials"
  verbs:
  - "get"
  - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "webhook-dnspod.secretReader" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "webhook-dnspod.secretReader" . }}
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "webhook-dnspod.fullname" . }}
    namespace: {{ .Release.Namespace }}
